In [1]:
import numpy as np


In [2]:
p=np.array([[1,7],[1,8],[2,8]])
print(p)

[[1 7]
 [1 8]
 [2 8]]


In [21]:
q=np.array([[7,1],[8,1],[1,5]])
print(q)

[[7 1]
 [8 1]
 [1 5]]


In [22]:
c=np.add(p,q)
print(c)

[[ 8  8]
 [ 9  9]
 [ 3 13]]


In [24]:
c2=np.subtract(q,p)

In [7]:
print(c2)

[[ 6 -6]
 [ 7 -7]
 [ 7 -7]]


In [13]:
c3=np.dot(p,q)
print(c3)

[[63  8 47]
 [71  9 53]
 [78 10 58]]


In [18]:
det=np.linalg.det(c3)
print(det)

0.0


In [25]:
invs=np.linalg.inv(c3)

LinAlgError: Singular matrix

In [27]:
c4=np.array([[63 , 8 ,37],
 [71 , 9 ,53],
 [78 ,10, 58]])

In [28]:
invs=np.linalg.inv(c4)

In [29]:
print(c4)

[[63  8 37]
 [71  9 53]
 [78 10 58]]
