In [1]:
import numpy as np

In [3]:
a=np.array([[2,-2,3],[1,1,1],[1,3,-1]])

In [4]:
print(a)

[[ 2 -2  3]
 [ 1  1  1]
 [ 1  3 -1]]


In [5]:
#eigen pair

In [7]:
values,vector=np.linalg.eig(a)

In [8]:
print(values)

[ 3.  1. -2.]


In [9]:
print(vector)

[[ 0.57735027  0.57735027 -0.61684937]
 [ 0.57735027 -0.57735027 -0.05607722]
 [ 0.57735027 -0.57735027  0.78508102]]


In [10]:
# these eigen vector are of unit lenght

In [11]:
a2=np.array([[2,0,0],[0,1,0],[0,0,-1]])

In [12]:
print(a2)

[[ 2  0  0]
 [ 0  1  0]
 [ 0  0 -1]]


In [13]:
values2,vector2=np.linalg.eig(a2)

In [14]:
print(values2)

[ 2.  1. -1.]


In [15]:
print(vector2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
